pipeline {
    agent any

    parameters {
        string(name: 'BRANCH', defaultValue: 'main', description: 'Git branch to build')
        string(name: 'BUILD_VERSION', defaultValue: '1.0.0', description: 'Version for the build')
    }

    environment {
        JAR_NAME = "hello-${params.BUILD_VERSION}.jar"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: "${params.BRANCH}", url: 'https://github.com/gratann/jenkins_task.git'
            }
        }

        stage('Build') {
            steps {
                dir('simple-java-app') {
                    echo "🔨 Building version ${params.BUILD_VERSION}..."
                    bat 'mvn compile'
                }
            }
        }

        stage('Package') {
            steps {
                dir('simple-java-app') {
                    echo "📦 Packaging as ${env.JAR_NAME}..."
                    bat "mvn package"
                    bat "ren target\\hello-1.0.jar ${env.JAR_NAME}"
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('simple-java-app') {
                    echo "🚀 Deploying ${env.JAR_NAME}..."
                    bat "java -cp target\\${env.JAR_NAME} Hello"
                }
            }
        }
    }
}
